//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nameless.BeetleTracker.Identity.Stores.Resources.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nameless.BeetleTracker.Identity.Stores.Resources.User.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO UsersInRoles VALUES (
        ///    @UserId,
        ///    @RoleId
        ///);.
        /// </summary>
        internal static string AddRoleToUser {
            get {
                return ResourceManager.GetString("AddRoleToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO UserClaims VALUES (
        ///    @Id,
        ///    @UserId,
        ///    @Type,
        ///    @Value
        ///);.
        /// </summary>
        internal static string AddUserClaim {
            get {
                return ResourceManager.GetString("AddUserClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO UserLogins VALUES (
        ///    @UserId,
        ///    @LoginProvider,
        ///    @ProviderKey
        ///);.
        /// </summary>
        internal static string AddUserLogin {
            get {
                return ResourceManager.GetString("AddUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Users VALUES (
        ///    @Id,
        ///    @UserName,
        ///    @FullName,
        ///    @AccessFailedCount,
        ///    @Email,
        ///    @EmailConfirmed,
        ///    @LockoutEnabled,
        ///    @LockoutEndDateUtc,
        ///    @PasswordHash,
        ///    @PhoneNumber,
        ///    @PhoneNumberConfirmed,
        ///    @TwoFactorEnabled,
        ///    @SecurityStamp,
        ///    @ProfilePicture,
        ///    @Attributes,
        ///    @State
        ///);.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///    State = @State
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    UserName,
        ///    FullName,
        ///    AccessFailedCount,
        ///    Email,
        ///    EmailConfirmed,
        ///    LockoutEnabled,
        ///    LockoutEndDateUtc,
        ///    PasswordHash,
        ///    PhoneNumber,
        ///    PhoneNumberConfirmed,
        ///    TwoFactorEnabled,
        ///    SecurityStamp,
        ///    ProfilePicture,
        ///    State,
        ///    Attributes
        ///FROM Users (NOLOCK);.
        /// </summary>
        internal static string FindUserByEmail {
            get {
                return ResourceManager.GetString("FindUserByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    UserName,
        ///    FullName,
        ///    AccessFailedCount,
        ///    Email,
        ///    EmailConfirmed,
        ///    LockoutEnabled,
        ///    LockoutEndDateUtc,
        ///    PasswordHash,
        ///    PhoneNumber,
        ///    PhoneNumberConfirmed,
        ///    TwoFactorEnabled,
        ///    SecurityStamp,
        ///    ProfilePicture,
        ///    State,
        ///    Attributes
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string FindUserById {
            get {
                return ResourceManager.GetString("FindUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Users.Id,
        ///    Users.UserName,
        ///    Users.FullName,
        ///    Users.AccessFailedCount,
        ///    Users.Email,
        ///    Users.EmailConfirmed,
        ///    Users.LockoutEnabled,
        ///    Users.LockoutEndDateUtc,
        ///    Users.PasswordHash,
        ///    Users.PhoneNumber,
        ///    Users.PhoneNumberConfirmed,
        ///    Users.TwoFactorEnabled,
        ///    Users.SecurityStamp,
        ///    Users.ProfilePicture,
        ///    Users.State,
        ///    Users.Attributes
        ///FROM Users (NOLOCK)
        ///INNER JOIN UsersLogins (NOLOCK) ON UsersLogins.UserId = Users.Id
        ///WHERE
        ///    UsersLogins.P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindUserByUserLogin {
            get {
                return ResourceManager.GetString("FindUserByUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    UserName,
        ///    FullName,
        ///    AccessFailedCount,
        ///    Email,
        ///    EmailConfirmed,
        ///    LockoutEnabled,
        ///    LockoutEndDateUtc,
        ///    PasswordHash,
        ///    PhoneNumber,
        ///    PhoneNumberConfirmed,
        ///    TwoFactorEnabled,
        ///    SecurityStamp,
        ///    ProfilePicture,
        ///    State,
        ///    Attributes
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    UserName = @UserName;.
        /// </summary>
        internal static string FindUserByUserName {
            get {
                return ResourceManager.GetString("FindUserByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id
        ///FROM Roles (NOLOCK)
        ///WHERE
        ///    Name = @Name.
        /// </summary>
        internal static string GetRoleIdByName {
            get {
                return ResourceManager.GetString("GetRoleIdByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    ISNULL(AccessFailedCount, 0)
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string GetUserAccessFailedCount {
            get {
                return ResourceManager.GetString("GetUserAccessFailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Type,
        ///    Value
        ///FROM UsersClaims (NOLOCK)
        ///WHERE
        ///    UserId = @UserId;.
        /// </summary>
        internal static string GetUserClaims {
            get {
                return ResourceManager.GetString("GetUserClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Email
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string GetUserEmail {
            get {
                return ResourceManager.GetString("GetUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Result BIT
        ///SELECT
        ///    @Result = EmailConfirmed
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    Id = @Id;
        ///SELECT ISNULL(@Result, 0) AS Result;.
        /// </summary>
        internal static string GetUserEmailConfirmed {
            get {
                return ResourceManager.GetString("GetUserEmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Result BIT
        ///SELECT
        ///    @Result = ISNULL(LockoutEnabled, 0)
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    Id = @Id;
        ///SELECT ISNULL(@Result, 0) AS Result;.
        /// </summary>
        internal static string GetUserLockoutEnabled {
            get {
                return ResourceManager.GetString("GetUserLockoutEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    ISNULL(LockoutEndDateUtc, &apos;0001-01-01&apos;)
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string GetUserLockoutEndDate {
            get {
                return ResourceManager.GetString("GetUserLockoutEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    LoginProvider,
        ///    ProviderKey
        ///FROM UsersLogins (NOLOCK)
        ///WHERE
        ///    UserId = @UserId;.
        /// </summary>
        internal static string GetUserLoginsByUser {
            get {
                return ResourceManager.GetString("GetUserLoginsByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    PasswordHash
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string GetUserPasswordHash {
            get {
                return ResourceManager.GetString("GetUserPasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    PhoneNumber
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string GetUserPhoneNumber {
            get {
                return ResourceManager.GetString("GetUserPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Result BIT
        ///SELECT
        ///    @Result = PhoneNumberConfirmed
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    Id = @Id;
        ///SELECT ISNULL(@Result, 0) AS Result;.
        /// </summary>
        internal static string GetUserPhoneNumberConfirmed {
            get {
                return ResourceManager.GetString("GetUserPhoneNumberConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Roles.Name
        ///FROM Roles (NOLOCK)
        ///INNER JOIN UsersInRoles (NOLOCK) ON UsersInRoles.RoleId = Roles.Id
        ///WHERE
        ///    UsersInRoles.UserId = @UserId;.
        /// </summary>
        internal static string GetUserRoles {
            get {
                return ResourceManager.GetString("GetUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    UserName,
        ///    FullName,
        ///    AccessFailedCount,
        ///    Email,
        ///    EmailConfirmed,
        ///    LockoutEnabled,
        ///    LockoutEndDateUtc,
        ///    PasswordHash,
        ///    PhoneNumber,
        ///    PhoneNumberConfirmed,
        ///    TwoFactorEnabled,
        ///    SecurityStamp,
        ///    ProfilePicture,
        ///    State,
        ///    Attributes
        ///FROM Users (NOLOCK);.
        /// </summary>
        internal static string GetUsers {
            get {
                return ResourceManager.GetString("GetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    SecurityStamp
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string GetUserSecurityStamp {
            get {
                return ResourceManager.GetString("GetUserSecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    TwoFactorEnabled
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string GetUserTwoFactorEnabled {
            get {
                return ResourceManager.GetString("GetUserTwoFactorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///    AccessFailedCount = ISNULL(AccessFailedCount, 0) + 1
        ///WHERE
        ///    Id = @Id;
        ///SELECT
        ///    AccessFailedCount
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string IncrementUserAccessFailedCount {
            get {
                return ResourceManager.GetString("IncrementUserAccessFailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Result BIT
        ///SELECT
        ///    @Result = 1
        ///FROM Roles (NOLOCK)
        ///INNER JOIN UsersInRoles (NOLOCK) ON UsersInRoles.RoleId = Roles.Id
        ///WHERE
        ///    UsersInRoles.UserId = @UserId
        ///AND Roles.Name = @RoleName;
        ///SELECT ISNULL(@Result, 0) AS Result;.
        /// </summary>
        internal static string IsUserInRole {
            get {
                return ResourceManager.GetString("IsUserInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM UserClaims
        ///WHERE
        ///    Type = @Type
        ///AND Value = @Value
        ///AND UserId = @UserId;.
        /// </summary>
        internal static string RemoveUserClaim {
            get {
                return ResourceManager.GetString("RemoveUserClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM UsersInRoles
        ///INNER JOIN Roles (NOLOCK) ON Roles.Id = UsersInRoles.RoleId
        ///WHERE
        ///    UsersInRoles.UserId = @UserId
        ///AND Roles.Name = @RoleName;.
        /// </summary>
        internal static string RemoveUserFromRole {
            get {
                return ResourceManager.GetString("RemoveUserFromRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM UserLogins
        ///WHERE
        ///    LoginProvider = @LoginProvider
        ///AND ProviderKey = @ProviderKey;.
        /// </summary>
        internal static string RemoveUserLogin {
            get {
                return ResourceManager.GetString("RemoveUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///    AccessFailedCount = 0
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string ResetUserAccessFailedCount {
            get {
                return ResourceManager.GetString("ResetUserAccessFailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///    Email = @Email
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string SetUserEmail {
            get {
                return ResourceManager.GetString("SetUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///    EmailConfirmed = @EmailConfirmed
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string SetUserEmailConfirmed {
            get {
                return ResourceManager.GetString("SetUserEmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///    LockoutEnabled = @LockoutEnabled
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string SetUserLockoutEnabled {
            get {
                return ResourceManager.GetString("SetUserLockoutEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///    LockoutEndDate = @LockoutEndDate
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string SetUserLockoutEndDate {
            get {
                return ResourceManager.GetString("SetUserLockoutEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///    PasswordHash = @PasswordHash
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string SetUserPasswordHash {
            get {
                return ResourceManager.GetString("SetUserPasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///    PhoneNumber = @PhoneNumber
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string SetUserPhoneNumber {
            get {
                return ResourceManager.GetString("SetUserPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///    PhoneNumberConfirmed = @PhoneNumberConfirmed
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string SetUserPhoneNumberConfirmed {
            get {
                return ResourceManager.GetString("SetUserPhoneNumberConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///    SecurityStamp = @SecurityStamp
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string SetUserSecurityStamp {
            get {
                return ResourceManager.GetString("SetUserSecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///    TwoFactorEnabled = @TwoFactorEnabled
        ///WHERE
        ///    Id = @Id;.
        /// </summary>
        internal static string SetUserTwoFactorEnabled {
            get {
                return ResourceManager.GetString("SetUserTwoFactorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users SET
        ///    UserName                = @UserName,
        ///    FullName                = @FullName,
        ///    AccessFailedCount       = @AccessFailedCount,
        ///    Email                   = @Email,
        ///    EmailConfirmed          = @EmailConfirmed,
        ///    LockoutEnabled          = @LockoutEnabled,
        ///    LockoutEndDateUtc       = @LockoutEndDateUtc,
        ///    PasswordHash            = @PasswordHash,
        ///    PhoneNumber             = @PhoneNumber,
        ///    PhoneNumberConfirmed    = @PhoneNumberConfirmed,
        ///    TwoFactorEnabled         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Result BIT
        ///SELECT
        ///    @Result = 1
        ///FROM Users (NOLOCK)
        ///WHERE
        ///    Id = @Id
        ///AND NOT PasswordHash IS NULL;
        ///SELECT ISNULL(@Result, 0) AS Result;.
        /// </summary>
        internal static string UserHasPasswordHash {
            get {
                return ResourceManager.GetString("UserHasPasswordHash", resourceCulture);
            }
        }
    }
}
